nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']  # This allows all origins. For production, specify allowed domains
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    paths:
        '^/api/': ~
